import * as WebApiClient from 'xrmtoolboxweb-webapiclient';
const POWERPLATFORM_ENV_URL = 'https://bsc-labs.crm.dynamics.com';
export const scopes = [`${POWERPLATFORM_ENV_URL}/user_impersonation`];
export const prepareWebApiRequest = (auth) => {
    let client = WebApiClient.Instance;
    client.ApiVersion = '9.1';
    client.Token = auth.accessToken;
    client.ClientUrl = POWERPLATFORM_ENV_URL;
};
export var DependentComponentType;
(function (DependentComponentType) {
    DependentComponentType[DependentComponentType["Entity"] = 1] = "Entity";
    DependentComponentType[DependentComponentType["Attribute"] = 2] = "Attribute";
    DependentComponentType[DependentComponentType["Relationship"] = 3] = "Relationship";
    DependentComponentType[DependentComponentType["Attribute Picklist Value"] = 4] = "Attribute Picklist Value";
    DependentComponentType[DependentComponentType["Attribute Lookup Value"] = 5] = "Attribute Lookup Value";
    DependentComponentType[DependentComponentType["View Attribute"] = 6] = "View Attribute";
    DependentComponentType[DependentComponentType["Localized Label"] = 7] = "Localized Label";
    DependentComponentType[DependentComponentType["Relationship Extra Condition"] = 8] = "Relationship Extra Condition";
    DependentComponentType[DependentComponentType["Option Set"] = 9] = "Option Set";
    DependentComponentType[DependentComponentType["Entity Relationship"] = 10] = "Entity Relationship";
    DependentComponentType[DependentComponentType["Entity Relationship Role"] = 11] = "Entity Relationship Role";
    DependentComponentType[DependentComponentType["Entity Relationship Relationships"] = 12] = "Entity Relationship Relationships";
    DependentComponentType[DependentComponentType["Managed Property"] = 13] = "Managed Property";
    DependentComponentType[DependentComponentType["Entity Key"] = 14] = "Entity Key";
    DependentComponentType[DependentComponentType["Privilege"] = 16] = "Privilege";
    DependentComponentType[DependentComponentType["PrivilegeObjectTypeCode"] = 17] = "PrivilegeObjectTypeCode";
    DependentComponentType[DependentComponentType["Role"] = 20] = "Role";
    DependentComponentType[DependentComponentType["Role Privilege"] = 21] = "Role Privilege";
    DependentComponentType[DependentComponentType["Display String"] = 22] = "Display String";
    DependentComponentType[DependentComponentType["Display String Map"] = 23] = "Display String Map";
    DependentComponentType[DependentComponentType["Form"] = 24] = "Form";
    DependentComponentType[DependentComponentType["Organization"] = 25] = "Organization";
    DependentComponentType[DependentComponentType["Saved Query"] = 26] = "Saved Query";
    DependentComponentType[DependentComponentType["Workflow"] = 29] = "Workflow";
    DependentComponentType[DependentComponentType["Report"] = 31] = "Report";
    DependentComponentType[DependentComponentType["Report Entity"] = 32] = "Report Entity";
    DependentComponentType[DependentComponentType["Report Category"] = 33] = "Report Category";
    DependentComponentType[DependentComponentType["Report Visibility"] = 34] = "Report Visibility";
    DependentComponentType[DependentComponentType["Attachment"] = 35] = "Attachment";
    DependentComponentType[DependentComponentType["Email Template"] = 36] = "Email Template";
    DependentComponentType[DependentComponentType["Contract Template"] = 37] = "Contract Template";
    DependentComponentType[DependentComponentType["KB Article Template"] = 38] = "KB Article Template";
    DependentComponentType[DependentComponentType["Mail Merge Template"] = 39] = "Mail Merge Template";
    DependentComponentType[DependentComponentType["Duplicate Rule"] = 44] = "Duplicate Rule";
    DependentComponentType[DependentComponentType["Duplicate Rule Condition"] = 45] = "Duplicate Rule Condition";
    DependentComponentType[DependentComponentType["Entity Map"] = 46] = "Entity Map";
    DependentComponentType[DependentComponentType["Attribute Map"] = 47] = "Attribute Map";
    DependentComponentType[DependentComponentType["Ribbon Command"] = 48] = "Ribbon Command";
    DependentComponentType[DependentComponentType["Ribbon Context Group"] = 49] = "Ribbon Context Group";
    DependentComponentType[DependentComponentType["Ribbon Customization"] = 50] = "Ribbon Customization";
    DependentComponentType[DependentComponentType["Ribbon Rule"] = 52] = "Ribbon Rule";
    DependentComponentType[DependentComponentType["Ribbon Tab To Command Map"] = 53] = "Ribbon Tab To Command Map";
    DependentComponentType[DependentComponentType["Ribbon Diff"] = 55] = "Ribbon Diff";
    DependentComponentType[DependentComponentType["Saved Query Visualization"] = 59] = "Saved Query Visualization";
    DependentComponentType[DependentComponentType["System Form"] = 60] = "System Form";
    DependentComponentType[DependentComponentType["Web Resource"] = 61] = "Web Resource";
    DependentComponentType[DependentComponentType["Site Map"] = 62] = "Site Map";
    DependentComponentType[DependentComponentType["Connection Role"] = 63] = "Connection Role";
    DependentComponentType[DependentComponentType["Complex Control"] = 64] = "Complex Control";
    DependentComponentType[DependentComponentType["Field Security Profile"] = 70] = "Field Security Profile";
    DependentComponentType[DependentComponentType["Field Permission"] = 71] = "Field Permission";
    DependentComponentType[DependentComponentType["Plugin Type"] = 90] = "Plugin Type";
    DependentComponentType[DependentComponentType["Plugin Assembly"] = 91] = "Plugin Assembly";
    DependentComponentType[DependentComponentType["SDK Message Processing Step"] = 92] = "SDK Message Processing Step";
    DependentComponentType[DependentComponentType["SDK Message Processing Step Image"] = 93] = "SDK Message Processing Step Image";
    DependentComponentType[DependentComponentType["Service Endpoint"] = 95] = "Service Endpoint";
    DependentComponentType[DependentComponentType["Routing Rule"] = 150] = "Routing Rule";
    DependentComponentType[DependentComponentType["Routing Rule Item"] = 151] = "Routing Rule Item";
    DependentComponentType[DependentComponentType["SLA"] = 152] = "SLA";
    DependentComponentType[DependentComponentType["SLA Item"] = 153] = "SLA Item";
    DependentComponentType[DependentComponentType["Convert Rule"] = 154] = "Convert Rule";
    DependentComponentType[DependentComponentType["Convert Rule Item"] = 155] = "Convert Rule Item";
    DependentComponentType[DependentComponentType["Hierarchy Rule"] = 65] = "Hierarchy Rule";
    DependentComponentType[DependentComponentType["Mobile Offline Profile"] = 161] = "Mobile Offline Profile";
    DependentComponentType[DependentComponentType["Mobile Offline Profile Item"] = 162] = "Mobile Offline Profile Item";
    DependentComponentType[DependentComponentType["Similarity Rule"] = 165] = "Similarity Rule";
    DependentComponentType[DependentComponentType["Custom Control"] = 66] = "Custom Control";
    DependentComponentType[DependentComponentType["Custom Control Default Config"] = 68] = "Custom Control Default Config";
    DependentComponentType[DependentComponentType["Data Source Mapping"] = 166] = "Data Source Mapping";
    DependentComponentType[DependentComponentType["SDKMessage"] = 201] = "SDKMessage";
    DependentComponentType[DependentComponentType["SDKMessageFilter"] = 202] = "SDKMessageFilter";
    DependentComponentType[DependentComponentType["SdkMessagePair"] = 203] = "SdkMessagePair";
    DependentComponentType[DependentComponentType["SdkMessageRequest"] = 204] = "SdkMessageRequest";
    DependentComponentType[DependentComponentType["SdkMessageRequestField"] = 205] = "SdkMessageRequestField";
    DependentComponentType[DependentComponentType["SdkMessageResponse"] = 206] = "SdkMessageResponse";
    DependentComponentType[DependentComponentType["SdkMessageResponseField"] = 207] = "SdkMessageResponseField";
    DependentComponentType[DependentComponentType["WebWizard"] = 210] = "WebWizard";
    DependentComponentType[DependentComponentType["Index"] = 18] = "Index";
    DependentComponentType[DependentComponentType["Import Map"] = 208] = "Import Map";
    DependentComponentType[DependentComponentType["Canvas App"] = 300] = "Canvas App";
    DependentComponentType[DependentComponentType["Connector1"] = 371] = "Connector1";
    DependentComponentType[DependentComponentType["Connector2"] = 372] = "Connector2";
    DependentComponentType[DependentComponentType["Environment Variable Definition"] = 380] = "Environment Variable Definition";
    DependentComponentType[DependentComponentType["Environment Variable Value"] = 381] = "Environment Variable Value";
    DependentComponentType[DependentComponentType["AI Project Type"] = 400] = "AI Project Type";
    DependentComponentType[DependentComponentType["AI Project"] = 401] = "AI Project";
    DependentComponentType[DependentComponentType["AI Configuration"] = 402] = "AI Configuration";
    DependentComponentType[DependentComponentType["Entity Analytics Configuration"] = 430] = "Entity Analytics Configuration";
    DependentComponentType[DependentComponentType["Attribute Image Configuration"] = 431] = "Attribute Image Configuration";
    DependentComponentType[DependentComponentType["Entity Image Configuration"] = 432] = "Entity Image Configuration";
})(DependentComponentType || (DependentComponentType = {}));
export const EntityFiltersEnum = {
    Entity: 'Entity',
    Attributes: 'Attributes',
    Privileges: 'Privileges',
    Relationships: 'Relationships',
    All: 'All',
};
const retrieveDependenciesForDeleteRequest = (params) => WebApiClient.Instance.Execute(WebApiClient.RetrieveDependenciesForDeleteRequest.with({ urlParams: params }));
